name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attr=2.5.2=h39aace5_0
  - binutils_impl_linux-64=2.45=default_hfdba357_104
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cgen=2025.1=pyhd8ed1ab_0
  - cmake=4.2.1=hc85cc9f_0
  - codepy=2025.1=pyhcf101f3_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda-gcc-specs=15.2.0=h53410ce_16
  - constantdict=2025.3=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - gcc=15.2.0=h0dff253_16
  - gcc_impl_linux-64=15.2.0=hc5723f1_16
  - genpy=2022.1=pyhcf101f3_1
  - gxx=15.2.0=h76987e4_16
  - gxx_impl_linux-64=15.2.0=hda75c37_16
  - immutabledict=4.2.2=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - isl=0.27=imath32_he9a3ec7_101
  - islpy=2026.1=py314he215357_100
  - kernel-headers_linux-64=5.14.0=he073ed8_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp19.1=19.1.7=default_h99862b1_7
  - libcurl=8.17.0=h4e3cde8_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libfabric=2.3.1=ha770c72_1
  - libfabric1=2.3.1=h6c8fc0a_1
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm19=19.1.7=hf7376ad_2
  - libllvmspirv19=19.1.13=hb733f1b_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb03c661_1
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsanitizer=15.2.0=h90f66d4_16
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libudev1=258.3=h6569c3e_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h031cc0b_0
  - libxml2-16=2.15.1=hf2a90c1_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-spirv-19=19.1.13=hb733f1b_0
  - mako=1.3.10=pyhcf101f3_1
  - markupsafe=3.0.3=pyh7db6752_0
  - mpi=1.0.1=mpich
  - mpich=4.3.2=h79b1c89_101
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.1=py314h2b28147_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pocl=7.1=h561d4bb_1
  - pocl-core=7.1=h022d097_1
  - pocl-cpu=7.1=h54225c5_1
  - pocl-cpu-minimal=7.1=h9e87ebc_1
  - pocl-cuda=7.1=ha08bc61_1
  - pocl-remote=7.1=h9e87ebc_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymbolic=2025.1=pyhc455866_0
  - pyopencl=2026.1.1=py314h3a4f467_0
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.14.2=h32b2ec7_100_cp314
  - python_abi=3.14=8_cp314
  - pytools=2025.2.5=pyhd8ed1ab_0
  - rdma-core=60.0=hecca717_0
  - readline=8.3=h853b02a_0
  - rhash=1.4.6=hb9d3cd8_1
  - siphash24=1.8=py314h5bd0f2a_2
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2024.3=h84d6215_0
  - sysroot_linux-64=2.34=h087de78_3
  - tk=8.6.13=noxft_h366c992_103
  - tomli=2.4.0=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h8577fbf_1
  - ucx=1.19.1=h567e125_0
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/zhangchenchen/miniconda3/envs/dev
